Repository DeveloperAcademy-POSTECH/2025-C4-A6-VisionITSM, pull requests merged in 2025-07, with the labels that each got.

#13 🐛 Bug: #12 swift6 <-> swif5간 Import기준 정상으로 반영
  Projects/VisionITSM/Packages/RealityKitContent/Package.swift
  Projects/VisionITSM/VisionITSM.xcodeproj/project.pbxproj
  Projects/VisionITSM/VisionITSM/Components/TrackingComponent.swift
  Projects/VisionITSM/VisionITSM/Components/Untitled.swift
  Projects/VisionITSM/VisionITSM/Utilities/TrackingSystem.swift
  Projects/VisionITSM/VisionITSM/ViewModels/AudienceSpawnViewModel.swift
  Projects/VisionITSM/VisionITSM/Views/Home/HomeView.swift
  Projects/VisionITSM/VisionITSM/Views/Immersive/ImmersiveView.swift
  Projects/VisionITSM/VisionITSM/VisionITSMApp.swift
Labels: bug

#33 ✨ Feature: #5 자식을 제거하지 않고, 살려두되 비활성화시켜서 감자 랜덤배치
  Projects/VisionITSM/Packages/RealityKitContent/Package.realitycomposerpro/PluginData/AF09ED6F-1707-48FD-8720-65B998362C09/ShaderGraphEditorPluginID/ShaderGraphEditorPluginID
  Projects/VisionITSM/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Projects/VisionITSM/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/coulson.rcuserdata
  Projects/VisionITSM/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Immersive.usda
  Projects/VisionITSM/VisionITSM/Views/Immersive/ImmersiveView.swift
Labels: enhancement

#39 ✨ Feature: #36 감자 정면에 조명 배치
  Projects/VisionITSM/VisionITSM/Views/Immersive/ImmersiveView.swift
Labels: enhancement

#42 ✨ Design: #40 슬라이드뷰 스폰용 엔티티 추가
  Projects/VisionITSM/Packages/RealityKitContent/Package.realitycomposerpro/ProjectData/main.json
  Projects/VisionITSM/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Projects/VisionITSM/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/Settings.rcprojectdata
  Projects/VisionITSM/Packages/RealityKitContent/Package.realitycomposerpro/WorkspaceData/coulson.rcuserdata
  Projects/VisionITSM/Packages/RealityKitContent/Sources/RealityKitContent/RealityKitContent.rkassets/Immersive.usda
  Projects/VisionITSM/VisionITSM/Views/Immersive/ImmersiveView.swift
  Projects/VisionITSM/VisionITSM/Views/Presentation/SlideView.swift
  Projects/VisionITSM/VisionITSM/VisionITSMApp.swift
Labels: documentation

#51 ✨ Feature: #50 윈도우 엔티티 씬에 있는 녀석 불러오깅
  Projects/VisionITSM/VisionITSM/Views/Immersive/ImmersiveView.swift
Labels: enhancement

#56 ✨ Feature: #54 졸음 애니메이션 추가
  Projects/VisionITSM/VisionITSM/Views/Immersive/ImmersiveView.swift
Labels: enhancement

#73 [feat] : 스크립트뷰 그리드 및 노트 수정, 결과 뷰 수정 (#71)
  Projects/VisionITSM/VisionITSM/Assets.xcassets/Home/GridLastButtonImage.imageset/Contents.json
  Projects/VisionITSM/VisionITSM/Assets.xcassets/Home/GridLastButtonImage.imageset/GridLastButtonImage.pdf
  Projects/VisionITSM/VisionITSM/Views/Home/HomeView.swift
  Projects/VisionITSM/VisionITSM/Views/Presentation/ScriptView.swift
  Projects/VisionITSM/VisionITSM/Views/Result/ResultView.swift
  Projects/VisionITSM/VisionITSM/Views/Setting/SettingView.swift
  Projects/VisionITSM/VisionITSM/VisionITSMApp.swift
Labels: enhancement
